height:
  - 500
toolbar:
  - styleselect | undo redo restoredraft | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | uploadimage | media | link | code codesample
plugins:
  - advlist
  - autosave
  - code
  - codesample
  - image
  - link
  - lists
  - media
  - table
  - uploadimage
uploadeimage: true
