toolbar:
  - styleselect | undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | image | link
plugins:
  - image
  - link
  - table
  - lists
  - advlist
  - code
