toolbar:
  - styleselect | undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | image | media | link | code codesample
plugins:
  - advlist
  - code
  - codesample
  - image
  - link
  - lists
  - media
  - table
